---

homebrew_taps:
  - homebrew/cask-fonts

homebrew_formulas:
  - ack
  - asdf
  - bash
  - bash-completion
  - ddgr
  - direnv
  - fd
  - fish
  - fop
  - fzf
  - fzy
  - git
  - git-extras
  - gh
  - gpg
  - htop
  - lazygit
  - libxslt
  - llvm
  - lua-language-server
  - make
  - mosh
  - mariadb@10.6
  - mysql@8.0
  - neofetch
  - nnn
  - pinentry-mac
  - readline
  - redis
  - ripgrep
  - stylua
  - terminal-notifier
  - the_silver_searcher
  - tmux
  - tree
  - unzip
  - wget
  - wxwidgets

  - go
  - golangci/tap/golangci-lint

  - ruby-build
  - libsodium # work project related
  - watchman # sorbet dep

  - rustup-init

homebrew_cask_applications:
  - 1password
  - 1password-cli
  - authy
  - dbeaver-community
  - cyberduck
  - docker
  - firefox
  - font-fantasque-sans-mono
  - font-fira-code-nerd-font
  - google-cloud-sdk
  - google-chrome
  - grammarly
  - iterm2
  - keycastr
  - logi-options-plus
  - microsoft-office
  - notion
  - homebrew/cask-versions/openemu-experimental
  - steam
  - transmission
  - zoom

osx_mas_formulas: [mas]
osx_mas_applications:
  - { id: "1319884285", name: Black Out }
  - { id: "975937182", name: Fantastical }
  - { id: "409183694", name: Keynote }
  - { id: "1263070803", name: Lungo }
  - { id: "1289197285", name: MindNode 5 }
  - { id: "1511185140", name: Moneywiz }
  - { id: "409201541", name: Pages }
  - { id: "1176895641", name: Spark }
  - { id: "747648890", name: Telegram }
  - { id: "497799835", name: Xcode }

# mas.yml
# Docs
# https://docs.ansible.com/ansible/2.5/modules/osx_defaults_module.html

# Section: OSX defaults ->>1
# -------------------------------------------------------------------------
osx_defaults:
  # Section: General ->>2
  # -------------------------------------------------------------------------
  - domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    meta: Disables open application confirmation dialog
  - domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark
  - domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1

  # Section: Menu bar ->>2
  # -------------------------------------------------------------------------
  - domain: com.apple.systemuiserver
    key: NSStatusItem Visible com.apple.menuextra.bluetooth
    type: int
    value: 1
  - domain: com.apple.systemuiserver
    key: NSStatusItem Visible com.apple.menuextra.volume
    type: int
    value: 1
  - domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES

  # Section: I/O ->>2
  # -------------------------------------------------------------------------

  # Section: Keyboard ->>3
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 18
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 3

    # Section: Mouse/Trackpad ->>3
  - domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
  - domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
  - domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: true
  - domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: true
  - domain: NSGlobalDomain
    key: com.apple.AppleMultitouchTrackpad.TrackpadFourFingerHorizSwipeGesture
    type: int
    value: 2

    # Section: All mighty measurement system ->>3
  - domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
  - domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true

    # Section: Password prompt when screensaver is shown ->>3
  - domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
  - domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0

  # Section: Finder ->>2
  # -------------------------------------------------------------------------
  - domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfHm
  - domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file://{{ ansible_env.HOME }}/
  - domain: com.apple.finder
    key: ShowRecentTags
    type: int
    value: 0
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: int
    value: 0
  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: int
    value: 0
  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: int
    value: 1
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  - domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  - domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  - domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

  # Section: Dock ->>2
  # -------------------------------------------------------------------------
  - domain: com.apple.dock
    key: magnification
    type: int
    value: 1
  - domain: com.apple.dock
    key: minimize-to-application
    type: int
    value: 1
  - domain: com.apple.dock
    key: largesize
    type: float
    value: 80
  - domain: com.apple.dock
    key: tilesize
    type: float
    value: 50
  - domain: com.apple.dock
    key: show-recents
    type: int
    value: 0

  # Section: Spotlight ->>2
  # -------------------------------------------------------------------------
  - domain: com.apple.lookup.shared
    key: LookupSuggestionsDisabled
    type: int
    value: 1

  # Section: iTerm2 ->>2
  # -------------------------------------------------------------------------
  - domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.HOME }}/.config/iterm2"
  - domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: int
    value: 1
  - domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    value:
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/Battery.menu"
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/Displays.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
      - "/System/Library/CoreServices/Menu Extras/Volume.menu"

osx_list_defaults:
  - domain: com.apple.Spotlight
    key: orderedItems
    type: array
    value:
      - '{enabled = 1;name = APPLICATIONS;}'
      - '{enabled = 1;name = "SYSTEM_PREFS";}'
      - '{enabled = 1;name = DIRECTORIES;}'
      - '{enabled = 1;name = PDF;}'
      - '{enabled = 1;name = "MENU_CONVERSION";}'
      - '{enabled = 1;name = "MENU_EXPRESSION";}'
      - '{enabled = 1;name = "MENU_DEFINITION";}'
      - '{enabled = 1;name = DOCUMENTS;}'
      - '{enabled = 1;name = CONTACT;}'
      - '{enabled = 0;name = MESSAGES;}'
      - '{enabled = 0;name = "EVENT_TODO";}'
      - '{enabled = 0;name = IMAGES;}'
      - '{enabled = 0;name = BOOKMARKS;}'
      - '{enabled = 0;name = MUSIC;}'
      - '{enabled = 0;name = FONTS;}'
      - '{enabled = 0;name = MOVIES;}'
      - '{enabled = 0;name = PRESENTATIONS;}'
      - '{enabled = 0;name = SPREADSHEETS;}'
      - '{enabled = 0;name = "MENU_OTHER";}'
      - '{enabled = 0;name = "MENU_SPOTLIGHT_SUGGESTIONS";}'
