---
ssh_source_path: ssh/keys
ssh_config: dotfiles/ssh_config
gpg_keys:
  - { public: gpg_public.key, private: gpg_private.key, id: jd@inkatze.com }

homebrew_taps:
  - homebrew/cask-fonts
  - adoptopenjdk/openjdk

homebrew_formulas:
  - ack
  - asdf
  - bash
  - bash-completion
  - ddgr
  - direnv
  - fd
  - fish
  - fop
  - fzf
  - fzy
  - git
  - git-extras
  - gh
  - gpg
  - htop
  - lazygit
  - libxslt
  - llvm
  - lua-language-server
  - make
  - mosh
  - mariadb@10.6
  - mysql@8.0
  - neofetch
  - nnn
  - pinentry-mac
  - readline
  - redis
  - ripgrep
  - stylua
  - terminal-notifier
  - the_silver_searcher
  - tmux
  - tree
  - unzip
  - wget
  - wxwidgets

  - go
  - golangci/tap/golangci-lint

  - ruby-build
  - libsodium # work project related
  - watchman # sorbet dep

  - rustup-init

homebrew_cask_applications:
  - 1password
  - 1password-cli
  - authy
  - cyberduck
  - db-browser-for-sqlite
  - DBngin
  - docker
  - firefox
  - font-fantasque-sans-mono
  - font-fira-code-nerd-font
  - google-cloud-sdk
  - google-chrome
  - grammarly
  - iterm2
  - keycastr
  - logi-options-plus
  - microsoft-office
  - notion
  - homebrew/cask-versions/openemu-experimental
  - steam
  - transmission
  - zoom

hombrew_dont_start_redis: false

# gpg.yml

gpg_formulas: [gpg]
gpg_base_source_path: gpg
gpg_agent_conf_source_file: "{{ gpg_base_source_path }}/gpg-agent.conf"

# dotfiles.yml

fish_config_source_path: fish
iterm2_plist_source_file: dotfiles/{{ current_env }}/com.googlecode.iterm2.plist
gitconfig_source_file: dotfiles/gitconfig
pylintrc_source_file: dotfiles/pylintrc
npmrc_source_file: dotfiles/npmrc
tmux_source_file: dotfiles/tmux.conf
mysql_config_source_file: dotfiles/my.cnf
import_js_config_source_file: dotfiles/importjs.js
default_mix_commands_source_file: dotfiles/default-mix-commands
tool_versions_source_file: dotfiles/tool-versions
default_npm_packages_source_file: dotfiles/default-npm-packages
default_gems_source_file: dotfiles/default-gems
default_python_packages_source_file: dotfiles/default-python-packages
asdfrc_source_file: dotfiles/asdfrc

# tmux
tmux_formulas:
  - tmux
  - urlview
