---

- src: https://github.com/inkatze/ansible-fish.git
  version: main
  name: fish_role

- src: https://github.com/inkatze/ansible-dotfiles.git
  version: main
  name: dotfiles_role

- src: https://github.com/inkatze/ansible-homebrew.git
  version: main
  name: homebrew_role

- src: https://github.com/inkatze/ansible-osx.git
  version: main
  name: osx_role

- src: https://github.com/inkatze/ansible-neovim.git
  version: main
  name: neovim_role
