- name: Creating iterm2 configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/iterm2"
    recurse: yes
    state: directory
  when: iterm2_plist_source_file | string

- name: Updating iterm2 configuration
  copy:
    src: "{{ iterm2_plist_source_file }}"
    dest: "{{ ansible_env.HOME }}/.config/iterm2"
  when: iterm2_plist_source_file | string
