- name: Creating iterm2 configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/iterm2"
    recurse: yes
    state: directory
  when: iterm2_plist_source_file | string

- name: Updating iterm2 configuration
  copy:
    src: "{{ iterm2_plist_source_file }}"
    dest: "{{ ansible_env.HOME }}/.config/iterm2"
  when: iterm2_plist_source_file | string

- name: Updating git configuration
  copy:
    src: "{{ gitconfig_source_file }}"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  when: gitconfig_source_file | string

- name: Updating my.cnf
  copy:
    src: "{{ mysql_config_source_file }}"
    dest: "{{ ansible_env.HOME }}/.my.cnf"
  when: mysql_config_source_file | string
