---

environments_homebrew_deps:
  - go
  - golangci/tap/golangci-lint
  - ruby-build
  - rustup-init
  - libsodium # work project related
  - watchman # sorbet dep

environments_mise_tools:
  - { name: nodejs, defaults: default-npm-packages }
  - { name: ruby, defaults: default-gems }
  - { name: java }
  - { name: python, defaults: default-python-packages }
  - { name: erlang }
  - { name: elixir, defaults: default-mix-commands }
  - { name: terraform }
  - { name: terraform-ls }
