---

- name: Check installed plugins
  ansible.builtin.command: asdf plugin-list
  register: plugin_list
  changed_when: false
  tags: [environments]

- name: Install nodejs asdf plugin
  ansible.builtin.command: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  changed_when: "'nodejs' not in plugin_list.stdout_lines"
  when: "'nodejs' not in plugin_list.stdout_lines"
  tags: [environments]

- name: Symlink default-npm-packages
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/environments/files/default-npm-packages"
    dest: "{{ ansible_env.HOME }}/.default-npm-packages"
    state: link
  tags: [environments]

- name: Install nodejs default version
  ansible.builtin.command: asdf install nodejs
  register: nodejs_installation_result
  changed_when: "'already installed' not in nodejs_installation_result.stdout"
  tags: [environments]
