#!/usr/bin/env bash
# Generate the private-project-identifier rules for .gitleaks.toml from the
# untracked machine-local identifier file (specs/dev-services REQ-D1.2,
# REQ-D1.4, REQ-D1.5; D-8, D-9).
#
# The identifier set itself never enters this repo outside the generated
# block: REQ-D1.1 forbids naming the consuming project in any committed
# artifact and carves out exactly the scanner configuration, because a rule
# cannot match an identifier without containing a pattern for it.
#
# Source file (untracked, mode 0600 or 0400 -- enforced, not assumed):
#   ${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/private-identifiers
# One identifier per line; blank lines and `#` comments ignored. A source that
# is absent, empty, unparseable, or readable beyond its owner is a visible
# refusal with a non-zero exit, never a silently narrower rule set (REQ-D1.4)
# -- a guard that quietly matches fewer identifiers than intended is worse
# than one that refuses.
#
# Usage:
#   gitleaks-identifier-rules.sh [--write | --stdout | --check]
#                                [--source FILE] [--repo-root DIR]
#
#   --write    splice the block into .gitleaks.toml (default)
#   --stdout   print the block, leaving the config untouched
#   --check    exit non-zero if the committed block is not what a fresh
#              generation produces (REQ-D1.5's byte-for-byte assertion)
#
# Exit: 0 ok · 2 source absent · 3 source empty · 4 unparseable source
#       5 committed block stale (--check) · 6 source mode not 600/400
#       64 usage error
set -euo pipefail

readonly E_ABSENT=2 E_EMPTY=3 E_UNPARSEABLE=4 E_STALE=5 E_MODE=6 E_USAGE=64

readonly BEGIN_MARKER='# >>> generated by scripts/gitleaks-identifier-rules.sh -- do not edit by hand >>>'
readonly END_MARKER='# <<< generated by scripts/gitleaks-identifier-rules.sh <<<'

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source_file="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/private-identifiers"
mode="write"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --write) mode="write" ;;
        --stdout) mode="stdout" ;;
        --check) mode="check" ;;
        --source)
            [[ $# -ge 2 ]] || { echo "ERROR: --source needs a path" >&2; exit "$E_USAGE"; }
            source_file="$2"; shift ;;
        --repo-root)
            [[ $# -ge 2 ]] || { echo "ERROR: --repo-root needs a path" >&2; exit "$E_USAGE"; }
            repo_root="$2"; shift ;;
        # Header block only, found by shape rather than by a line range: a
        # fixed range silently starts printing code when the header grows.
        -h|--help)
            awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' \
                "${BASH_SOURCE[0]}"
            exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; exit "$E_USAGE" ;;
    esac
    shift
done

config="$repo_root/.gitleaks.toml"

# --- read and validate the source ------------------------------------------
# The charset is deliberately narrow. It is what makes the values safe to
# interpolate into a TOML literal string and a regex alternation below: no
# quotes, no whitespace, no regex metacharacter except `.`, which is escaped.
readonly IDENTIFIER_RE='^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$'

if [[ ! -f "$source_file" ]]; then
    cat >&2 <<EOF
ERROR: the identifier source file is absent: $source_file

Refusing to generate a narrower rule set (REQ-D1.4). Create it, mode 0600,
with one identifier per line:

    umask 077 && \$EDITOR "$source_file"

It is machine-local and untracked by design (D-9); its contents must not
reach this repo outside the block this script generates.
EOF
    exit "$E_ABSENT"
fi

# The file is documented, and required by Task 1's Done-when, to be 0600.
# Checked rather than assumed, matching scripts/ssh-lan-config-sync.sh's
# posture for the machine-local file it reads. GNU stat first, BSD second.
perms=$(stat -c '%a' "$source_file" 2>/dev/null || stat -f '%Lp' "$source_file" 2>/dev/null || echo '')
case "$perms" in
    600|400) ;;
    '')
        echo "ERROR: could not stat the identifier source file: $source_file" >&2
        exit "$E_MODE" ;;
    *)
        cat >&2 <<EOF
ERROR: $source_file is mode $perms; must be 600 or 400

    chmod 600 "$source_file"

The file names a private project, so it is kept unreadable by other accounts
on the machine (D-9). Refusing rather than generating from a file this host
has left readable.
EOF
        exit "$E_MODE" ;;
esac

identifiers=()
lineno=0
while IFS= read -r line || [[ -n "$line" ]]; do
    lineno=$((lineno + 1))
    line="${line%%#*}"
    # Trim surrounding whitespace.
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    if [[ ! "$line" =~ $IDENTIFIER_RE ]]; then
        # The offending value is deliberately not echoed: this output can
        # reach a terminal or CI log, and the file's whole point is that its
        # contents stay off shared surfaces.
        cat >&2 <<EOF
ERROR: unparseable identifier at $source_file line $lineno

Refusing rather than skipping the line (REQ-D1.4). Each identifier must match
$IDENTIFIER_RE -- start alphanumeric, then alphanumerics, dot, underscore or
hyphen, 2-64 characters. Value withheld from this message on purpose.
EOF
        exit "$E_UNPARSEABLE"
    fi
    identifiers+=("$line")
done <"$source_file"

if [[ "${#identifiers[@]}" -eq 0 ]]; then
    cat >&2 <<EOF
ERROR: the source file contains no identifiers: $source_file

It exists but holds only blank lines or comments. Refusing rather than
emitting a rule that matches nothing (REQ-D1.4).
EOF
    exit "$E_EMPTY"
fi

# Case-fold then sort -u, so the block is identical for a given set whatever
# order or casing the source lists it in (REQ-D1.5). The rule matches
# case-insensitively, so folding loses nothing.
mapfile -t identifiers < <(
    printf '%s\n' "${identifiers[@]}" | tr '[:upper:]' '[:lower:]' | LC_ALL=C sort -u
)

# --- build the rule block ---------------------------------------------------
escape_regex() { printf '%s' "$1" | sed 's/[][^$.*+?(){}|\\]/\\&/g'; }

alternation=""
for id in "${identifiers[@]}"; do
    [[ -n "$alternation" ]] && alternation+="|"
    alternation+=$(escape_regex "$id")
done

# The config names the identifiers in its own rule, so it must allowlist
# itself or the scanner flags its own patterns.
allowlist_paths=('^\.gitleaks\.toml$')
if git -C "$repo_root" rev-parse --git-dir >/dev/null 2>&1; then
    # NUL-separated: a tracked path may legally contain a newline.
    while IFS= read -r -d '' path; do
        [[ -n "$path" ]] && allowlist_paths+=("^$(escape_regex "$path")\$")
    done < <(
        git -C "$repo_root" grep -l -z -i -E -e "$alternation" -- \
            . ':(exclude).gitleaks.toml' 2>/dev/null | LC_ALL=C sort -z -u || true
    )
fi

emit_block() {
    cat <<EOF
$BEGIN_MARKER
# Private project identifier rules (specs/dev-services REQ-D1.2, D-8, D-9).
# Generated from an untracked machine-local file; regenerate with
# \`scripts/gitleaks-identifier-rules.sh --write\` after changing the set, and
# assert this block is current with \`--check\`.
#
# REQ-D1.1 forbids naming the consuming project in any artifact this repo
# commits and carves out this configuration alone: a rule cannot match an
# identifier without containing a pattern for it. That carve-out is D-8's
# accepted self-contradiction, not an oversight.
[[rules]]
id = "private-project-identifier"
description = "Private project identifier (public-repo hygiene, REQ-D1.2)"
regex = '''(?i)\b(?:$alternation)\b'''
tags = ["private-identifier", "req-d1.2"]

  # Path-scoped allowlist for the identifiers' pre-existing tracked
  # occurrences (REQ-D1.3), so editing these files for unrelated reasons does
  # not fail the hook. Scoped to known paths: a new file still fires.
  #
  # REMOVAL CONDITION: delete this allowlist, and this whole generated block
  # with it, when the successor repo-hygiene bundle scrubs the identifiers
  # from tracked artifacts and history (or makes the repo private). It is a
  # visible marker for that bundle, not a permanent exemption.
  [[rules.allowlists]]
  description = "Pre-existing tracked occurrences (REQ-D1.3; see removal condition above)"
  paths = [
EOF
    for path in "${allowlist_paths[@]}"; do
        printf "    '''%s''',\n" "$path"
    done
    cat <<EOF
  ]
$END_MARKER
EOF
}

case "$mode" in
    stdout)
        emit_block
        ;;
    write|check)
        if [[ ! -f "$config" ]]; then
            echo "ERROR: $config does not exist" >&2
            exit "$E_USAGE"
        fi
        # Everything outside the marker pair is preserved byte for byte; an
        # absent pair means the block has never been written, so append it.
        # Matched as whole lines with awk rather than sed addresses: the
        # markers name this script, so they contain `/`.
        before=$(awk -v m="$BEGIN_MARKER" '$0 == m { exit } { print }' "$config")
        if grep -qxF "$BEGIN_MARKER" "$config"; then
            after=$(awk -v m="$END_MARKER" 'found { print } $0 == m { found = 1 }' "$config")
        else
            after=""
        fi
        rendered=$(
            if [[ -n "$before" ]]; then printf '%s\n' "$before"; fi
            emit_block
            if [[ -n "$after" ]]; then printf '%s\n' "$after"; fi
        )
        if [[ "$mode" == check ]]; then
            if [[ "$rendered" == "$(cat "$config")" ]]; then
                exit 0
            fi
            echo "ERROR: the block in $config is not what a fresh generation produces." >&2
            echo "Re-run: scripts/gitleaks-identifier-rules.sh --write" >&2
            exit "$E_STALE"
        fi
        # Written alongside the target and renamed, so a failure part-way
        # cannot leave a truncated scanner config behind.
        tmp=$(mktemp "$config.XXXXXX")
        printf '%s\n' "$rendered" >"$tmp"
        chmod --reference="$config" "$tmp" 2>/dev/null || chmod 644 "$tmp"
        mv "$tmp" "$config"
        echo "wrote ${#identifiers[@]} identifier(s) and" \
            "${#allowlist_paths[@]} allowlist path(s) to $config"
        ;;
esac
