---

- name: Download neovim nightly
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-macos-{{ ansible_architecture }}.tar.gz
    dest: "{{ ansible_env.HOME }}/.local"
    remote_src: true
  tags: [neovim]

- name: Symlink neovim binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/nvim-macos-{{ ansible_architecture }}/bin/nvim"
    dest: /usr/local/bin/nvim
    state: link
  tags: [neovim]

- name: Symlink neovim configuration
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/neovim/files/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
  tags: [neovim]

- name: Restore neovim plugins
  ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
  changed_when: false
  tags: [neovim]

- name: Install neovim plugins
  ansible.builtin.command: nvim --headless '+Lazy! install' +qa
  changed_when: false
  tags: [neovim]

- name: Install treesitter modules
  ansible.builtin.command: nvim --headless '+TSInstallSync all' +qa
  changed_when: false
  tags: [neovim]

- name: Upgrade neovim plugins
  ansible.builtin.command: nvim --headless '+Lazy! sync' +qa
  changed_when: false
  tags: [upgrade]

- name: Upgrade treesitter modules
  ansible.builtin.command: nvim --headless '+TSUpdateSync all' +qa
  changed_when: false
  tags: [upgrade]
